name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install dependencies
      run: sudo apt install libjpeg-turbo8-dev libglu1-mesa-dev

    - name: Build binaries
      run: make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
         name: z80pack-ubuntu
         path: .

